IoTWeb/Controllers/PanelController.cs
using CapaDeDatos;
using CapaDeDatos.Entidades;
using IoTWeb.App_Start;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IoTWeb.Controllers
{
    public class PanelController : Controller
    {
        //GenericRepository<Proyecto> repository = new GenericRepository<Proyecto>();
        // GET: Panel
        public ActionResult Index()
        {
            var proyectos = Servicios.repositoryProyectos.Query(u => u.IdUsuario == ((Usuario)Session["Usuario"]).Id);
            return View(proyectos);
        }


        public ActionResult Create()
        {
            Proyecto p = new Proyecto();
            p.IdUsuario = ((Usuario)Session["Usuario"]).Id;
            return View(p);
        }

        public ActionResult Crear(Proyecto proyecto)
        {
            if (Servicios.repositoryProyectos.Create(proyecto) != null)
            {
                return View("Index", Servicios.repositoryProyectos.Query(u => u.IdUsuario == ((Usuario)Session["Usuario"]).Id));
            }
            else
            {
                ViewBag.Mensaje("Error al crear el proyecto");
                return View("Create", ((Usuario)Session["Usuario"]));
            }
        }

        public ActionResult Edit(string id)
        {
            ViewBag.Mensaje = "";
            return View("Edit", Servicios.repositoryProyectos.SearchById(id));
        }

        public ActionResult Editar(Proyecto proyecto)
        {
            if (Servicios.repositoryProyectos.Update(proyecto) != null)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Mensaje = "Error al editar el proyecto";
                return View("Edit", proyecto);
            }
        }

        public ActionResult Delete(string id)
        {
            if (!Servicios.repositoryProyectos.Delete(id))
            {
                ViewBag.Mensaje = "No se pudo borrar el Proyecto";
            }
            return RedirectToAction("Index");
        }
        public ActionResult Details(string id)
        {
            Session["Proyecto"] = Servicios.repositoryProyectos.SearchById(id);
            return RedirectToAction("Index", "Sensores");
        }
    }
}

IoTWeb/Views/Panel/Create.cshtml
@model CapaDeDatos.Entidades.Proyecto

@{
    ViewBag.Title = "Crear Proyecto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Crear Proyecto</h2>


@using (Html.BeginForm("Crear", "Panel")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Proyecto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdUsuario, new { htmlAttributes = new { @Hidden="true" } })
                @Html.ValidationMessageFor(model => model.IdUsuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IoTWeb/Views/Panel/Edit.cshtml
@model CapaDeDatos.Entidades.Proyecto

@{
    ViewBag.Title = "Editar Proyecto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar Proyecto @Model.Nombre</h2>


@using (Html.BeginForm("Editar","Panel"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Proyecto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdUsuario, new { htmlAttributes = new { @Hidden="true" } })
                @Html.ValidationMessageFor(model => model.IdUsuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IoTWeb/Views/Panel/Index.cshtml
@model IEnumerable<CapaDeDatos.Entidades.Proyecto>

@{
    ViewBag.Title = "Proyectos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Proyectos</h2>

<p>
    @Html.ActionLink("Crear Nuevo", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Ver", "Details", new { id=item.Id }) |
            @Html.ActionLink("Eliminar", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>